export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL'
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET'

export const ORDERS_DETAIL_REQUEST = 'ORDERS_DETAIL_REQUEST'
export const ORDERS_DETAIL_SUCCESS = 'ORDERS_DETAIL_SUCCESS'
export const ORDERS_DETAIL_FAIL = 'ORDERS_DETAIL_FAIL'
export const ORDERS_DETAIL_RESET = 'ORDERS_DETAIL_RESET'
